### ISSUE TITLE
onmt_preprocess failed

### ISSUE THREAD

**Issue by hariesramdhani** [FerdiantJoshua/question-generator#1]
Hi, thank you for the tidy source code, I tried to replicate your experiment in Google Colab but when I ran the following code (it's the snippet from the `src/onmt/config/gru_045.sh` source code)

```
!onmt_preprocess -train_src 'data/processed/train/squad_id_split0.9_cased_source.txt' -train_tgt 'data/processed/train/squad_id_split0.9_cased_target.txt' \
    -valid_src 'data/processed/val/squad_id_split0.9_cased_source.txt' -valid_tgt 'data/processed/val/squad_id_split0.9_cased_target.txt' \
    -save_data 'data/processed/onmt/squad_id_split0.9_cased' \
    -overwrite \
    -dynamic_dict \
    -src_vocab_size 50000 \
    -tgt_vocab_size 30000 \
    -src_seq_length 60 \
    -tgt_seq_length 20 \
    -num_threads 1
```

It returned the following error

```
[2020-11-25 11:41:07,147 INFO] Extracting features...
[2020-11-25 11:41:07,147 INFO]  * number of source features: 3.
[2020-11-25 11:41:07,147 INFO]  * number of target features: 0.
[2020-11-25 11:41:07,147 INFO] Building `Fields` object...
[2020-11-25 11:41:07,148 INFO] Building & saving training data...
[2020-11-25 11:41:08,225 INFO] Building shard 0.
[2020-11-25 11:41:36,965 INFO]  * saving 0th train data shard to data/processed/onmt/squad_id_split0.9_cased.train.0.pt.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.6/dist-packages/onmt/bin/preprocess.py", line 101, in process_one_shard
    dataset.save(data_path)
  File "/usr/local/lib/python3.6/dist-packages/onmt/inputters/dataset_base.py", line 158, in save
    torch.save(self, path)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 327, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 212, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 193, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/onmt/squad_id_split0.9_cased.train.0.pt'
```

Any idea on what's the cause of this error? 

Also I think there's a typo in the following code 
```
python src/preprocess/prepare_data.py \
    --dataset_name=squad_id \
    --train_squad_path=data/processed/train-v2.0-translated_fixed_enhanced.json \
    --dev_squad_path=data/processed/train-v2.0-translated_fixed_enhanced.json \
    --train_val_split=0.9 \
    --src_max_len=70 \
    --tgt_max_len=20 \
    --seed 42
```
the `dev_squad_path` used the train path instead of dev path

Thank you, hoping you're having a nice day.

Best regards,

Haries

**Comment by FerdiantJoshua** [comment]
Hello, thanks you also for trying to reproduce my experiment.

Ah sorry for some typos and problems in my scripts. You're right, I missed some details before publishing them.

However it's quite simple I guess; the directory `data/processed/onmt` does not exist. Just create the directory: `mkdir data/processed/onmt`, and then try to re-run the script.

**Comment by hariesramdhani** [comment]
Thank you, appreciate the quick response and yes silly me, should have seen it coming. I'll flag this issue as closed.
